package com.itgd.transcoder.bean;

import com.amazonaws.services.cloudfront.model.PriceClass;

// Generated May 31, 2013 7:39:18 PM by Hibernate Tools 3.2.1.GA



/**
 * AmazobAwsJobOutputDesc generated by hbm2java
 */
public class AmazobAwsJobOutputDesc  implements java.io.Serializable {


     private Integer bitrateId;
     private Integer profileId;
     private Integer bitrate;
     private String presetId;
     private String folderName;
     private String format;
     private String filenameSuffix;
     private Integer hlsFormat;
     private Integer autoId;
     private Integer jobDescId;
     private String keySuffix;
    

    public Integer getAutoId() {
		return autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	public Integer getJobDescId() {
		return jobDescId;
	}

	public void setJobDescId(Integer jobDescId) {
		this.jobDescId = jobDescId;
	}

	public String getKeySuffix() {
		return keySuffix;
	}

	public void setKeySuffix(String keySuffix) {
		this.keySuffix = keySuffix;
	}

	public Integer getHlsFormat() {
		return hlsFormat;
	}

	public void setHlsFormat(Integer hlsFormat) {
		this.hlsFormat = hlsFormat;
	}

	public AmazobAwsJobOutputDesc() {
    }
    
    public String getFormat() {
		return format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public AmazobAwsJobOutputDesc(int profileId, String presetId) {
        this.profileId = profileId;
        this.presetId = presetId;
    }
    
    public AmazobAwsJobOutputDesc(Integer profileId,Integer bitrate, String folderName, String filenameSuffix,String format, String presetId) {
       this.profileId = profileId;
       this.bitrate=bitrate;
       this.folderName = folderName;
       this.filenameSuffix = filenameSuffix;
       this.presetId = presetId;
       this.format=format;
    }
   
    public Integer getBitrateId() {
        return this.bitrateId;
    }
    
    public void setBitrateId(Integer bitrateId) {
        this.bitrateId = bitrateId;
    }
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public Integer getBitrate() {
        return this.bitrate;
    }
    
    public void setBitrate(Integer bitrate) {
        this.bitrate = bitrate;
    }
    public String getFolderName() {
        return this.folderName;
    }
    
    public void setFolderName(String folderName) {
        this.folderName = folderName;
    }
    public String getFilenameSuffix() {
        return this.filenameSuffix;
    }
    
    public void setFilenameSuffix(String filenameSuffix) {
        this.filenameSuffix = filenameSuffix;
    }

    public String getPresetId() {
        return presetId;
    }

    public void setPresetId(String presetId) {
        this.presetId = presetId;
    }

}


