package com.itgd.transcoder.bean;
// Generated May 31, 2013 7:39:18 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
/**
 * AmazonAwsJobDesc generated by hbm2java
 */
public class AmazonWebsiteDetails  implements java.io.Serializable {


     private Integer websiteId;
     private String websiteName;
     private Integer websiteStatus;
     private String websiteSource;
   

    public AmazonWebsiteDetails() {
    }
    
    public AmazonWebsiteDetails(Integer websiteId,String websiteName, Integer websiteStatus, String websiteSource) {
    	  this.websiteId=websiteId;
    	  this.websiteName=websiteName;
    	  this.websiteStatus=websiteStatus;
    	  this.websiteSource=websiteSource;
    }

	public Integer getWebsiteId() {
		return websiteId;
	}

	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	public String getWebsiteName() {
		return websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public Integer getWebsiteStatus() {
		return websiteStatus;
	}

	public void setWebsiteStatus(Integer websiteStatus) {
		this.websiteStatus = websiteStatus;
	}

	public String getWebsiteSource() {
		return websiteSource;
	}

	public void setWebsiteSource(String websiteSource) {
		this.websiteSource = websiteSource;
	}
      
}


