package com.itgd.transcoder.bean;
// Generated May 31, 2013 7:39:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AmazonTranscoding generated by hbm2java
 */
public class AmazonTranscoding  implements java.io.Serializable {


     private Integer transInputId;
     private String jobId;
     private String sourceFileName;
     private String jobStatus;
     private Integer profileId;
     private String inputPath;
     private Date jobCreationTime;
     private Date jobCompletionTime;
     private Integer websiteId;
     private String fileDuration;
     private String previewImage;
     private String jobMarker;
     private String pipelineId;
     
    public AmazonTranscoding() {
    }

    public AmazonTranscoding(Integer transInputId,String jobId, String sourceFileName, String jobStatus, Integer profileId, String inputPath, Date jobCreationTime, Date jobCompletionTime, Integer websiteId, String fileDuration, String previewImage, String jobMarker,String pipelineId) {
       this.transInputId=transInputId;
       this.jobId = jobId;
       this.sourceFileName = sourceFileName;
       this.jobStatus = jobStatus;
       this.profileId = profileId;
       this.inputPath = inputPath;
       this.jobCreationTime = jobCreationTime;
       this.jobCompletionTime = jobCompletionTime;
       this.websiteId = websiteId;
       this.fileDuration=fileDuration;
       this.previewImage = previewImage;
       this.jobMarker=jobMarker;
       this.pipelineId=pipelineId; 
       
    }
   	public Integer getTransInputId() {
        return this.transInputId;
    }
    
    public void setTransInputId(Integer transInputId) {
        this.transInputId = transInputId;
    }
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
    public String getSourceFileName() {
        return this.sourceFileName;
    }
    
    public void setSourceFileName(String sourceFileName) {
        this.sourceFileName = sourceFileName;
    }
    public String getJobStatus() {
        return this.jobStatus;
    }
    
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }
    public String getPipelineId() {
        return this.pipelineId;
    }
    
    public void setPipelineId(String pipelineId) {
        this.pipelineId = pipelineId;
    }
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public String getInputPath() {
        return this.inputPath;
    }
    
    public void setInputPath(String inputPath) {
        this.inputPath = inputPath;
    }
    public Date getJobCreationTime() {
        return this.jobCreationTime;
    } 
    public void setJobCreationTime(Date jobCreationTime) {
        this.jobCreationTime = jobCreationTime;
    }
    public Date getJobCompletionTime() {
        return this.jobCompletionTime;
    }
    
    public void setJobCompletionTime(Date jobCompletionTime) {
        this.jobCompletionTime = jobCompletionTime;
    }
    public Integer getWebsiteId() {
        return this.websiteId;
    }
    
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }
    public String getJobMarker() {
        return this.jobMarker;
    }
    public void setJobMarker(String jobMarker) {
        this.jobMarker = jobMarker;
    }
    public void setFileDuration(String fileDuration) {
        this.fileDuration = fileDuration;
    }
    public String getFileDuration() {
        return this.fileDuration;
    }
    public String getPreviewImage() {
        return this.previewImage;
    }
    public void setPreviewImage(String previewImage) {
        this.previewImage = previewImage;
    }


}


