package com.itgd.transcoder.bean;
// Generated May 31, 2013 7:39:18 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * AmazonAwsJobDesc generated by hbm2java
 */
public class AmazonAwsJobDesc  implements java.io.Serializable {


     private Integer profileId;
     private String pipelineId;
     private String profileName;
     private Date jobDescCreatedBy;
     private Date jobDescCreatedTime;
     private String jobDescDiscription;
     private String inputBasePath;
     private String processBasePath;
     private String processedBasePath;
     private String errorBasePath;
     private String outputBasePath;
     private String bucketInput;
     private String jobExeStatus;
     private String bucketoutput;
     private Integer websiteId;
     private Integer transInputId;
     private String watermark="";
     private String watermarkPlace="";
     private String xmlPostPath="";
     private String xmlReadPath="";

    public AmazonAwsJobDesc() {
    }
    
    public AmazonAwsJobDesc(String xmlPostPath,String xmlReadPath,Integer transInputId,Integer profileId,String pipelineId, String profileName,Date jobDescCreatedBy,Date jobDescCreatedTime,String jobDescDiscription, String inputBasePath, String processBasePath, String processedBasePath, String errorBasePath, String outputBasePath,String transcodFolderName, String bucketInput, String jobExeStatus, String bucketoutput, Integer websiteId, String watermark, String watermarkPlace) {
    	  this.transInputId=transInputId;
    	  this.profileId=profileId;
    	  this.pipelineId=pipelineId;
    	  this.profileName=profileName;
    	  this.jobDescCreatedBy=jobDescCreatedBy;
    	  this.jobDescCreatedTime=jobDescCreatedTime;
    	  this.jobDescDiscription=jobDescDiscription;
    	  this.inputBasePath=inputBasePath;
    	  this.processBasePath=processBasePath;
    	  this.processedBasePath=processedBasePath;
    	  this.errorBasePath=errorBasePath;
    	  this.outputBasePath=outputBasePath;
    	  this.bucketInput=bucketInput;
    	  this.jobExeStatus=jobExeStatus;
    	  this.bucketoutput=bucketoutput;
    	  this.websiteId=websiteId;
    	  this.watermark=watermark;
    	  this.watermarkPlace=watermarkPlace;
    	  this.xmlPostPath=xmlPostPath;
    	  this.xmlReadPath=xmlReadPath;
    }
 
    public void setXmlReadPath(String xmlReadPath) {
		this.xmlReadPath = xmlReadPath;
	}public String getXmlReadPath() {
		return xmlReadPath;
	}    
    public void setXmlPostPath(String xmlPostPath) {
		this.xmlPostPath = xmlPostPath;
	}public String getXmlPostPath() {
		return xmlPostPath;
	}
    public Integer getTransInputId() {
        return this.transInputId;
    }
    
    public void setTransInputId(Integer transInputId) {
        this.transInputId = transInputId;
    } 
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public String getPipelineId() {
        return this.pipelineId;
    }
    
    public void setPipelineId(String pipelineId) {
        this.pipelineId = pipelineId;
    }
    public String getProfileName() {
        return this.profileName;
    } 
    
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }
    public Date getJobDescCreatedBy() {
        return this.jobDescCreatedBy;
    }
    
    public void setJobDescCreatedBy(Date jobDescCreatedBy) {
        this.jobDescCreatedBy = jobDescCreatedBy;
    }
    
    
    public Date getJobDescCreatedTime() {
        return this.jobDescCreatedTime;
    }
    
    public void setJobDescCreatedTime(Date jobDescCreatedTime) {
        this.jobDescCreatedTime = jobDescCreatedTime;
    }
    
    public String getJobDescDiscription() {
        return this.jobDescDiscription;
    }
    
    public void setJobDescDiscription(String jobDescDiscription) {
        this.jobDescDiscription = jobDescDiscription;
    }
    public String getInputBasePath() {
        return this.inputBasePath;
    }
    
    public void setInputBasePath(String inputBasePath) {
        this.inputBasePath = inputBasePath;
    }
    public String getProcessBasePath() {
        return this.processBasePath;
    }
    
    public void setProcessBasePath(String processBasePath) {
        this.processBasePath = processBasePath;
    }
    public String getProcessedBasePath() {
        return this.processedBasePath;
    }
    
    public void setProcessedBasePath(String processedBasePath) {
        this.processedBasePath = processedBasePath;
    }
    public String getErrorBasePath() {
        return this.errorBasePath;
    }
    
    public void setErrorBasePath(String errorBasePath) {
        this.errorBasePath = errorBasePath;
    }
    public String getOutputBasePath() {
        return this.outputBasePath;
    }
    
    public void setOutputBasePath(String outputBasePath) {
        this.outputBasePath = outputBasePath;
    }

    public String getBucketInput() {
        return bucketInput;
    }

    public void setBucketInput(String bucketInput) {
        this.bucketInput = bucketInput;
    }
    public String getJobExeStatus() {
        return jobExeStatus;
    }

    public void setJobExeStatus(String jobExeStatus) {
        this.jobExeStatus = jobExeStatus;
    }
   
    public Integer getWebsiteId() {
        return this.websiteId;
    }
    
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

	public String getBucketoutput() {
		return bucketoutput;
	}

	public void setBucketoutput(String bucketoutput) {
		this.bucketoutput = bucketoutput;
	}

	public String getWatermark() {
		return watermark;
	}

	public void setWatermark(String watermark) {
		this.watermark = watermark;
	}

	public String getWatermarkPlace() {
		return watermarkPlace;
	}

	public void setWatermarkPlace(String watermarkPlace) {
		this.watermarkPlace = watermarkPlace;
	}
   
}


