package com.itgd.transcoder.bean;
// Generated May 31, 2013 7:39:18 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Joboutput generated by hbm2java
 */
public class Joboutput  implements java.io.Serializable {


     private Integer transIntputId;
     private Integer transOutputid;
     private String outputPath;
     private Integer bitrateId;
     private String outputStatus;
     private String outputStatusDetail;
     private String jobId;
     private Date fileCreationTime;
     private Date fileCompletionTime;
     private String fileDuration;
     private String outputPresetId;
     private String vedioType;
     private String inputPath;
     private String inputjobStatus;
     private String source_file_name;
     private int webSiteId;
     private String webSiteName;
     private int profileId;
     
     
     
  

	public Joboutput() {
    }

    public Joboutput(int profileId,String webSiteName,int webSiteId ,Integer transOutputid,Integer transIntputId,String outputPath,Integer bitrateId, String outputStatus, String outputStatusDetail, String jobId, Date fileCreationTime, Date fileCompletionTime,String fileDuration,String outputPresetId, String vedioType) {
    	this.transOutputid=transOutputid;
       this.transIntputId = transIntputId;
       this.outputPath = outputPath;
       this.bitrateId = bitrateId;
       this.outputStatus = outputStatus;
       this.outputStatusDetail = outputStatusDetail;
       this.jobId = jobId;
       this.fileCreationTime = fileCreationTime;
       this.fileCompletionTime = fileCompletionTime;
       this.fileDuration=fileDuration;
       this.fileDuration=fileDuration;
       this.vedioType=vedioType;
       this.webSiteId=webSiteId;
       this.webSiteName=webSiteName;
       this.profileId=profileId;
    }
   
    public void setProfileId(int profileId) {
		this.profileId = profileId;
	}public int getProfileId() {
		return profileId;
	}
    public void setWebSiteId(int webSiteId) {
		this.webSiteId = webSiteId;
	}public int getWebSiteId() {
		return webSiteId;
	}public void setWebSiteName(String webSiteName) {
		this.webSiteName = webSiteName;
	}public String getWebSiteName() {
		return webSiteName;
	}
    public void setSource_file_name(String source_file_name) {
		this.source_file_name = source_file_name;
	}public String getSource_file_name() {
		return source_file_name;
	}
    public void setInputjobStatus(String inputjobStatus) {
		this.inputjobStatus = inputjobStatus;
	}public String getInputjobStatus() {
		return inputjobStatus;
	}
    public void setInputPath(String inputPath) {
		this.inputPath = inputPath;
	}public String getInputPath() {
		return inputPath;
	}
    public String getVedioType() {
		return vedioType;
	}

	public void setVedioType(String vedioType) {
		this.vedioType = vedioType;
	}
    
    public Integer getTransOutputid() {
        return this.transOutputid;
    }
    
    public void setTransOutputid(Integer transOutputid) {
        this.transOutputid = transOutputid;
    }
    public Integer getTransIntputId() {
        return this.transIntputId;
    }
    
    public void setTransIntputId(Integer transIntputId) {
        this.transIntputId = transIntputId;
    }
    public String getOutputPath() {
        return this.outputPath;
    }
    
    public void setOutputPath(String outputPath) {
        this.outputPath = outputPath;
    }
    public Integer getBitrateId() {
        return this.bitrateId;
    }
    
    public void setBitrateId(Integer bitrateId) {
        this.bitrateId = bitrateId;
    }
    public String getOutputStatus() {
        return this.outputStatus;
    }
    public void setOutputStatus(String outputStatus) {
        this.outputStatus = outputStatus;
    }
    public String getOutputStatusDetail() {
        return this.outputStatusDetail;
    }
    
    public void setOutputStatusDetail(String outputStatusDetail) {
        this.outputStatusDetail = outputStatusDetail;
    }
    
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
    
    public Date getFileCreationTime() {
        return this.fileCreationTime;
    }
    
    public void setFileCreationTime(Date fileCreationTime) {
        this.fileCreationTime = fileCreationTime;
    }
    public Date getFileCompletionTime() {
        return this.fileCompletionTime;
    }
    
    public void setFileCompletionTime(Date fileCompletionTime) {
        this.fileCompletionTime = fileCompletionTime;
    }
    
    public String getOutputPresetId() {
        return this.outputPresetId;
    }
    
    public void setOutputPresetId(String outputPresetId) {
        this.outputPresetId = outputPresetId;
    }
    
    public String getFileDuration() {
        return this.fileDuration;
    }
    
    public void setFileDuration(String fileDuration) {
        this.fileDuration = fileDuration;
    }
    
  
    
 }


