package com.itgd.transcoder.bean;
// Generated May 31, 2013 7:39:18 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Joboutput generated by hbm2java
 */
public class TranscodingProcessLog  implements java.io.Serializable {


     private Integer transProcessId;
     private String sourcePath;
     private String destinationPath;
     private Date fileCreationTime;
 	private Integer profileId;
    private String outputStatus;
     
     public Integer getTransProcessId() {
		return transProcessId;
	}
	public void setTransProcessId(Integer transProcessId) {
		this.transProcessId = transProcessId;
	}
	public String getSourcePath() {
		return sourcePath;
	}
	public void setSourcePath(String sourcePath) {
		this.sourcePath = sourcePath;
	}
	public String getDestinationPath() {
		return destinationPath;
	}
	public void setDestinationPath(String destinationPath) {
		this.destinationPath = destinationPath;
	}
	public Date getFileCreationTime() {
		return fileCreationTime;
	}
	public void setFileCreationTime(Date fileCreationTime) {
		this.fileCreationTime = fileCreationTime;
	}
	public Integer getProfileId() {
		return profileId;
	}
	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}
	public String getOutputStatus() {
		return outputStatus;
	}
	public void setOutputStatus(String outputStatus) {
		this.outputStatus = outputStatus;
	}

    
     
     
  
}